using Content.Shared.Movement.Components;
using Content.Shared.CCVar;
using Content.Shared.Sectors;
using Content.Shared.Sectors.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleNavControl : BaseShuttleControl
{
    [Dependency] private readonly IMapManager _mapManager = default!;
    [Dependency] private readonly IConfigurationManager _configuration = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedSectorSystem _sectors;
    private readonly SharedTransformSystem _transform;

    /// <summary>
    /// Used to transform all of the radar objects. Typically is a shuttle console parented to a grid.
    /// </summary>
    private EntityCoordinates? _coordinates;

    /// <summary>
    /// Entity of controlling console
    /// </summary>
    private EntityUid? _consoleEntity;

    private Angle? _rotation;

    private Dictionary<NetEntity, List<DockingPortState>> _docks = new();
    private Dictionary<SpaceSector, string> _sectorWeatherEvents = new();

    public bool ShowIFF { get; set; } = true;
    public bool ShowDocks { get; set; } = true;
    public bool RotateWithEntity { get; set; } = true;
    public IFFSortMode SortMode { get; set; } = IFFSortMode.None;

    private const float SortFadeMultiplier = 0.1f;

    /// <summary>
    /// Raised if the user left-clicks on the radar control with the relevant entitycoordinates.
    /// </summary>
    public Action<EntityCoordinates>? OnRadarClick;

    private List<Entity<MapGridComponent>> _grids = new();

    public ShuttleNavControl() : base(64f, 256f, 256f)
    {
        RobustXamlLoader.Load(this);
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _sectors = EntManager.System<SharedSectorSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _coordinates = coordinates;
        _rotation = angle;
    }

    public void SetConsole(EntityUid? consoleEntity)
    {
        _consoleEntity = consoleEntity;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (_coordinates == null || _rotation == null || args.Function != EngineKeyFunctions.UIClick ||
            OnRadarClick == null)
        {
            return;
        }

        var a = InverseScalePosition(args.RelativePosition);
        var relativeWorldPos = new Vector2(a.X, -a.Y);
        relativeWorldPos = _rotation.Value.RotateVec(relativeWorldPos);
        var coords = _coordinates.Value.Offset(relativeWorldPos);
        OnRadarClick?.Invoke(coords);
    }

    /// <summary>
    /// Gets the entitycoordinates of where the mouseposition is, relative to the control.
    /// </summary>
    [PublicAPI]
    public EntityCoordinates GetMouseCoordinates(ScreenCoordinates screen)
    {
        if (_coordinates == null || _rotation == null)
        {
            return EntityCoordinates.Invalid;
        }

        var pos = screen.Position / UIScale - GlobalPosition;

        var a = InverseScalePosition(pos);
        var relativeWorldPos = new Vector2(a.X, -a.Y);
        relativeWorldPos = _rotation.Value.RotateVec(relativeWorldPos);
        var coords = _coordinates.Value.Offset(relativeWorldPos);
        return coords;
    }

    public void UpdateState(NavInterfaceState state)
    {
        SetMatrix(EntManager.GetCoordinates(state.Coordinates), state.Angle);

        WorldMaxRange = state.MaxRange;

        if (WorldMaxRange < WorldRange)
        {
            ActualRadarRange = WorldMaxRange;
        }

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);

        RotateWithEntity = state.RotateWithEntity;

        _docks = state.Docks;
        _sectorWeatherEvents = state.SectorWeatherEvents;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        DrawBacking(handle);
        DrawCircles(handle);

        // No data
        if (_coordinates == null || _rotation == null)
        {
            return;
        }

        var xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        var fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();
        var bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();
        var mapBoundsQuery = EntManager.GetEntityQuery<MapBoundsComponent>();

        if (!xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform)
            || xform.MapID == MapId.Nullspace)
        {
            return;
        }

        var mapPos = _transform.ToMapCoordinates(_coordinates.Value);

        var sectorName = _sectors.GetSectorName(_sectors.GetSector(mapPos.Position));
        var sectorText = Loc.GetString("shuttle-console-sector-value", ("sector", sectorName));
        handle.DrawString(Font, new Vector2(8f, 8f), sectorText, Color.White);

        var posMatrix = Matrix3Helpers.CreateTransform(_coordinates.Value.Position, _rotation.Value);
        var ourEntRot = RotateWithEntity ? _transform.GetWorldRotation(xform) : _rotation.Value;
        var ourEntMatrix = Matrix3Helpers.CreateTransform(_transform.GetWorldPosition(xform), ourEntRot);

        var shuttleToWorld = Matrix3x2.Multiply(posMatrix, ourEntMatrix);
        Matrix3x2.Invert(shuttleToWorld, out var worldToShuttle);
        var shuttleToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) * Matrix3x2.CreateTranslation(MidPointVector);
        var worldToView = worldToShuttle * shuttleToView;

        DrawSectorBoundaries(handle, worldToView);

        var map = _transform.GetMap(xform.Coordinates);
        if (map != null && mapBoundsQuery.TryGetComponent(map, out var mapBounds) && mapBounds != null)
        {
            var mapBoundsToWorld = Matrix3Helpers.CreateTransform(Vector2.Zero, Angle.Zero);
            var mapBoundsToView = mapBoundsToWorld * worldToShuttle * shuttleToView;
            var gridCentre = Vector2.Transform(Vector2.Zero, mapBoundsToView);
            handle.DrawCircle(gridCentre, MinimapScale * mapBounds.Radius, Color.Red, false);
        }

        // Draw our grid in detail
        var ourGridId = xform.GridUid;
        if (EntManager.TryGetComponent<MapGridComponent>(ourGridId, out var ourGrid) &&
            fixturesQuery.HasComponent(ourGridId.Value))
        {
            var ourGridToWorld = _transform.GetWorldMatrix(ourGridId.Value);
            var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
            var ourGridToView = ourGridToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(ourGridId.Value, self: true);

            DrawGrid(handle, ourGridToView, (ourGridId.Value, ourGrid), color);
            DrawDocks(handle, ourGridId.Value, ourGridToView);
        }

        // Draw radar position on the station
        const float radarVertRadius = 2f;
        var radarPosVerts = new Vector2[]
        {
            ScalePosition(new Vector2(0f, -radarVertRadius)),
            ScalePosition(new Vector2(radarVertRadius / 2f, 0f)),
            ScalePosition(new Vector2(0f, radarVertRadius)),
            ScalePosition(new Vector2(radarVertRadius / -2f, 0f)),
        };

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, radarPosVerts, Color.Lime);

        var rot = ourEntRot + _rotation.Value;
        var viewBounds = new Box2Rotated(new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(mapPos.Position), rot, mapPos.Position);
        var viewAABB = viewBounds.CalcBoundingBox();

        DrawNorthLine(handle, rot);

        _grids.Clear();
        _mapManager.FindGridsIntersecting(xform.MapID, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), ref _grids, approx: true, includeMap: false);

        // Draw other grids... differently
        foreach (var grid in _grids)
        {
            var gUid = grid.Owner;
            if (gUid == ourGridId || !fixturesQuery.HasComponent(gUid))
                continue;

            var gridBody = bodyQuery.GetComponent(gUid);
            EntManager.TryGetComponent<IFFComponent>(gUid, out var iff);

            if (!_shuttles.CanDraw(gUid, gridBody, iff))
                continue;

            var curGridToWorld = _transform.GetWorldMatrix(gUid);
            var curGridToView = curGridToWorld * worldToShuttle * shuttleToView;

            var labelColor = _shuttles.GetIFFColor(grid, self: false, iff);
            var coordColor = new Color(labelColor.R * 0.8f, labelColor.G * 0.8f, labelColor.B * 0.8f, 0.5f);

            if (ShouldFade(iff))
            {
                labelColor = labelColor.WithAlpha(labelColor.A * SortFadeMultiplier);
                coordColor = coordColor.WithAlpha(coordColor.A * SortFadeMultiplier);
            }

            // Others default:
            // Color.FromHex("#FFC000FF")
            // Hostile default: Color.Firebrick
            var labelName = _shuttles.GetIFFLabel(grid, self: false, iff);
            var designation = iff?.Designation ?? IFFDesignation.Ship;
            var labelScale = designation == IFFDesignation.Station ? 1.3f : 1f;

            if (ShowIFF &&
                 labelName != null)
            {
                var gridBounds = grid.Comp.LocalAABB;

                var gridCentreInView = Vector2.Transform(gridBody.LocalCenter, curGridToView);
                var gridCenterInWorld = Vector2.Transform(gridBody.LocalCenter, curGridToWorld);
                var gridDistance = (gridCenterInWorld - _transform.GetMapCoordinates(xform).Position).Length();
                var labelText = Loc.GetString("shuttle-console-iff-label", ("name", labelName),
                    ("distance", $"{gridDistance:0.0}"));

                var coordsText = $"({gridCenterInWorld.X:0.0}, {gridCenterInWorld.Y:0.0})";

                // yes 1.0 scale is intended here.
                var labelDimensions = handle.GetDimensions(Font, labelText, labelScale);
                var coordsDimensions = handle.GetDimensions(Font, coordsText, 0.7f);

                // y-offset the control to always render below the grid (vertically)
                var yOffset = Math.Max(gridBounds.Height, gridBounds.Width) * MinimapScale / 1.8f;

                // The actual position in the UI.
                var gridScaledPosition = gridCentreInView - new Vector2(0, -yOffset);

                // Normalize the grid position if it exceeds the viewport bounds
                // normalizing it instead of clamping it preserves the direction of the vector and prevents corner-hugging
                var gridOffset = gridScaledPosition / PixelSize - new Vector2(0.5f, 0.5f);
                var offsetMax = Math.Max(Math.Abs(gridOffset.X), Math.Abs(gridOffset.Y)) * 2f;
                if (offsetMax > 1)
                {
                    gridOffset = new Vector2(gridOffset.X / offsetMax, gridOffset.Y / offsetMax);

                    gridScaledPosition = (gridOffset + new Vector2(0.5f, 0.5f)) * PixelSize;
                }

                var labelUiPosition = gridScaledPosition - new Vector2(labelDimensions.X / 2f, 0);
                var coordUiPosition = gridScaledPosition - new Vector2(coordsDimensions.X / 2f, -labelDimensions.Y);

                // clamp the IFF label's UI position to within the viewport extents so it hugs the edges of the viewport
                // coord label intentionally isn't clamped so we don't get ugly clutter at the edges
                var controlExtents = PixelSize - new Vector2(labelDimensions.X, labelDimensions.Y); //new Vector2(labelDimensions.X * 2f, labelDimensions.Y);
                labelUiPosition = Vector2.Clamp(labelUiPosition, Vector2.Zero, controlExtents);

                // draw IFF label
                handle.DrawString(Font, labelUiPosition, labelText, labelScale, labelColor);

                // only draw coords label if close enough
                if (offsetMax < 1)
                {
                    handle.DrawString(Font, coordUiPosition, coordsText, 0.7f, coordColor);
                }
            }

            // Detailed view
            var gridAABB = curGridToWorld.TransformBox(grid.Comp.LocalAABB);

            // Skip drawing if it's out of range.
            if (!gridAABB.Intersects(viewAABB))
                continue;

            DrawGrid(handle, curGridToView, grid, labelColor);
            DrawDocks(handle, gUid, curGridToView);
        }

        // If we've set the controlling console, and it's on a different grid
        // to the shuttle itself, then draw an additional marker to help the
        // player determine where they are relative to the shuttle.
        if (_consoleEntity != null && xformQuery.TryGetComponent(_consoleEntity, out var consoleXform))
        {
            if (consoleXform.ParentUid != _coordinates.Value.EntityId)
            {
                var consolePositionWorld = _transform.GetWorldPosition((EntityUid)_consoleEntity);
                var p = Vector2.Transform(consolePositionWorld, worldToView);
                handle.DrawCircle(p, 5, Color.ToSrgb(Color.Cyan), true);
            }
        }

    }

    private bool ShouldFade(IFFComponent? iff)
    {
        return !_shuttles.MatchesSortTag(iff, SortMode);
    }

    private void DrawSectorBoundaries(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        var centerRadius = _configuration.GetCVar(CCVars.SectorCenterRadius);
        var maxRadius = _configuration.GetCVar(CCVars.SectorMaxRadius);

        var origin = Vector2.Transform(Vector2.Zero, worldToView);
        var centerEdge = Vector2.Transform(new Vector2(centerRadius, 0f), worldToView);
        var scaledCenterRadius = (centerEdge - origin).Length();

        var ringColor = new Color(0.43f, 0.66f, 0.87f, 0.34f);
        var borderColor = new Color(0.34f, 0.56f, 0.77f, 0.24f);

        handle.DrawCircle(origin, scaledCenterRadius, ringColor, false);

        // Octant boundaries: 22.5 + n * 45 keeps sector centers on cardinals and diagonals.
        for (var i = 0; i < 8; i++)
        {
            DrawSectorBoundaryRay(handle, worldToView, centerRadius, maxRadius, SectorHelpers.EastLowerBoundary + (45f * i), borderColor);
        }

        foreach (var (sector, weatherId) in _sectorWeatherEvents)
        {
            if (!_prototypes.TryIndex<SectorWeatherPrototype>(weatherId, out var weather))
                continue;

            var weatherColor = Color.ToSrgb(weather.BorderColor);

            if (sector == SpaceSector.Center)
            {
                handle.DrawCircle(origin, scaledCenterRadius, weatherColor, false);
                continue;
            }

            if (!TryGetSectorBoundaryAngles(sector, out var firstBoundary, out var secondBoundary))
                continue;

            DrawSectorBoundaryRay(handle, worldToView, centerRadius, maxRadius, firstBoundary, weatherColor);
            DrawSectorBoundaryRay(handle, worldToView, centerRadius, maxRadius, secondBoundary, weatherColor);
                DrawSectorArc(handle, worldToView, centerRadius, firstBoundary, secondBoundary, weatherColor);
        }
    }

    private static bool TryGetSectorBoundaryAngles(SpaceSector sector, out float firstBoundary, out float secondBoundary)
    {
        switch (sector)
        {
            case SpaceSector.NorthEast:
                firstBoundary = SectorHelpers.EastLowerBoundary;
                secondBoundary = SectorHelpers.NorthEastUpperBoundary;
                return true;
            case SpaceSector.North:
                firstBoundary = SectorHelpers.NorthEastUpperBoundary;
                secondBoundary = SectorHelpers.NorthUpperBoundary;
                return true;
            case SpaceSector.NorthWest:
                firstBoundary = SectorHelpers.NorthUpperBoundary;
                secondBoundary = SectorHelpers.NorthWestUpperBoundary;
                return true;
            case SpaceSector.West:
                firstBoundary = SectorHelpers.NorthWestUpperBoundary;
                secondBoundary = SectorHelpers.WestUpperBoundary;
                return true;
            case SpaceSector.SouthWest:
                firstBoundary = SectorHelpers.WestUpperBoundary;
                secondBoundary = SectorHelpers.SouthWestUpperBoundary;
                return true;
            case SpaceSector.South:
                firstBoundary = SectorHelpers.SouthWestUpperBoundary;
                secondBoundary = SectorHelpers.SouthUpperBoundary;
                return true;
            case SpaceSector.SouthEast:
                firstBoundary = SectorHelpers.SouthUpperBoundary;
                secondBoundary = SectorHelpers.SouthEastUpperBoundary;
                return true;
            case SpaceSector.East:
                firstBoundary = SectorHelpers.SouthEastUpperBoundary;
                secondBoundary = SectorHelpers.EastLowerBoundary;
                return true;
            default:
                firstBoundary = 0f;
                secondBoundary = 0f;
                return false;
        }
    }

    private static void DrawSectorBoundaryRay(
        DrawingHandleScreen handle,
        Matrix3x2 worldToView,
        float centerRadius,
        float maxRadius,
        float boundaryDegrees,
        Color color)
    {
        var boundaryDirection = Angle.FromDegrees(boundaryDegrees).ToVec();
        var startWorld = boundaryDirection * centerRadius;
        var endpointWorld = boundaryDirection * maxRadius;
        var startView = Vector2.Transform(startWorld, worldToView);
        var endpointView = Vector2.Transform(endpointWorld, worldToView);
        handle.DrawLine(startView, endpointView, color);
    }

        private static void DrawSectorArc(
            DrawingHandleScreen handle,
            Matrix3x2 worldToView,
            float centerRadius,
            float startDegrees,
            float endDegrees,
            Color color)
        {
            const int segments = 12;
            // Handle wrap-around (e.g. East sector: 337.5° → 22.5°)
            var range = endDegrees > startDegrees
                ? endDegrees - startDegrees
                : endDegrees + 360f - startDegrees;

            Vector2? prev = null;
            for (var i = 0; i <= segments; i++)
            {
                var t = i / (float) segments;
                var dir = Angle.FromDegrees(startDegrees + range * t).ToVec();
                var viewPos = Vector2.Transform(dir * centerRadius, worldToView);
                if (prev.HasValue)
                    handle.DrawLine(prev.Value, viewPos, color);
                prev = viewPos;
            }
        }

    private void DrawDocks(DrawingHandleScreen handle, EntityUid uid, Matrix3x2 gridToView)
    {
        if (!ShowDocks)
            return;

        const float DockScale = 0.6f;
        var nent = EntManager.GetNetEntity(uid);

        const float sqrt2 = 1.41421356f;
        const float dockRadius = DockScale * sqrt2;
        // Worst-case bounds used to cull a dock:
        Box2 viewBounds = new Box2(
            -dockRadius * UIScale,
            -dockRadius * UIScale,
            (Size.X + dockRadius) * UIScale,
            (Size.Y + dockRadius) * UIScale);

        if (_docks.TryGetValue(nent, out var docks))
        {
            foreach (var state in docks)
            {
                var position = state.Coordinates.Position;

                var positionInView = Vector2.Transform(position, gridToView);
                if (!viewBounds.Contains(positionInView))
                {
                    continue;
                }

                var color = Color.ToSrgb(state.HighlightedColor);

                var verts = new[]
                {
                    Vector2.Transform(position + new Vector2(-DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(-DockScale, DockScale), gridToView),
                };

                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, verts, color.WithAlpha(0.8f));
                handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
            }
        }
    }

    private Vector2 InverseScalePosition(Vector2 value)
    {
        return (value - MidPointVector) / MinimapScale;
    }
}
