# Configuration preset for the official Persistence SS14 server.
# This file was written with the expectation that persistBase would be loaded first.
# Related docs https://docs.spacestation14.com/en/general-development/tips/config-file-reference.html

[game]
soft_max_players = 150
autosaveenabled = true
autosaveinterval = 60
panic_bunker.show_reason = true
panic_bunker.custom_reason = "The server is not accepting new connections at this time."

[hub]
tags = "lang:en,region:am_n_w,rp:high"

[server]
rules_file = "PersistRuleset"

[ooc]
enable_during_round = false

[looc]
enabled_dead = true
enabled_crit = true

[ic]
flavor_text = true
punctuation = true

[lore]
year_offset = 200

[tips]
enabled = false

[atmos]
max_explosion_range = 4

[admin]
new_player_threshold = 600
alert.min_players_sharing_connection = 2
