using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MessageBoard.UI;
[GenerateTypedNameReferences]
public sealed partial class CreateEntry : DefaultWindow
{
    public enum EntryType : byte
    {
        Public,
        Direct
    }

    public EntryType CurrentEntryType = EntryType.Public;

    public CreateEntry()
    {
        RobustXamlLoader.Load(this);
    }
}

