using System.Globalization;
using System.Linq;
using Content.Shared.CCVar;
using Content.Shared.Sectors;
using Content.Shared.Sectors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Console;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class AdminSectorWindow : DefaultWindow
{
    [Dependency] private readonly IConsoleHost _console = default!;
    [Dependency] private readonly IConfigurationManager _configuration = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public AdminSectorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var sectors = Enum.GetNames<SpaceSector>();
        for (var i = 0; i < sectors.Length; i++)
        {
            var sector = sectors[i];
            SectorSelector.AddItem(sector);
            SectorSelector.SetItemMetadata(i, sector);
        }

        var weatherPrototypes = _prototypes.EnumeratePrototypes<SectorWeatherPrototype>()
            .Select(p => p.ID)
            .OrderBy(id => id)
            .ToList();

        for (var i = 0; i < weatherPrototypes.Count; i++)
        {
            var weatherId = weatherPrototypes[i];
            var displayName = weatherId;
            if (_prototypes.TryIndex<SectorWeatherPrototype>(weatherId, out var proto) &&
                !string.IsNullOrWhiteSpace(proto.Name))
            {
                displayName = Loc.GetString(proto.Name);
            }
            WeatherIdSelector.AddItem(displayName);
            WeatherIdSelector.SetItemMetadata(i, weatherId);
        }

        WeatherIdSelector.OnItemSelected += args => WeatherIdSelector.SelectId(args.Id);

        SectorSelector.OnItemSelected += args =>
        {
            SectorSelector.SelectId(args.Id);
            UpdateSectorNameEdit();
        };
        SectorSelector.SelectId(0);
        if (weatherPrototypes.Count > 0)
            WeatherIdSelector.SelectId(0);
        UpdateSectorNameEdit();

        SetWeatherButton.OnPressed += _ => ApplyWeather();
        ClearWeatherButton.OnPressed += _ => ClearWeather();
        SetSectorNameButton.OnPressed += _ => SetSectorName();
        ClearSectorNameButton.OnPressed += _ => ClearSectorName();
        SetCenterRadiusButton.OnPressed += _ => SetCVarRadius("sector.center_radius", CenterRadiusEdit.Text);
        SetMaxRadiusButton.OnPressed += _ => SetCVarRadius("sector.max_radius", MaxRadiusEdit.Text);
    }

    private string SelectedSector => SectorSelector.SelectedMetadata as string ?? SpaceSector.Center.ToString();

    private void ApplyWeather()
    {
        var weatherId = WeatherIdSelector.SelectedMetadata as string;
        if (string.IsNullOrWhiteSpace(weatherId))
            return;

        _console.ExecuteCommand($"sudo sectorweather {SelectedSector} {weatherId}");
    }

    private void ClearWeather()
    {
        _console.ExecuteCommand($"sudo sectorweather {SelectedSector} clear");
    }

    private void SetSectorName()
    {
        var name = SectorNameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        SetStringCVar(GetSectorNameCVarName(), name);
    }

    private void ClearSectorName()
    {
        SetStringCVar(GetSectorNameCVarName(), string.Empty);
        SectorNameEdit.Text = string.Empty;
    }

    private void SetCVarRadius(string cvarName, string radiusText)
    {
        if (!float.TryParse(radiusText, NumberStyles.Float, CultureInfo.InvariantCulture, out var radius))
            return;

        _console.ExecuteCommand($"sudo cvar {cvarName} {radius.ToString(CultureInfo.InvariantCulture)}");
    }

    private void SetStringCVar(string cvarName, string value)
    {
        var escaped = value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        _console.ExecuteCommand($"sudo cvar {cvarName} \"{escaped}\"");
    }

    private void UpdateSectorNameEdit()
    {
        SectorNameEdit.Text = _configuration.GetCVar(GetSectorNameCVarDef());
    }

    private string GetSectorNameCVarName()
    {
        return GetSectorNameCVarDef().Name;
    }

    private CVarDef<string> GetSectorNameCVarDef()
    {
        if (!Enum.TryParse<SpaceSector>(SelectedSector, out var sector))
            sector = SpaceSector.Center;

        return SharedSectorSystem.GetSectorNameCVar(sector);
    }
}
