using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Content.Shared._Art.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IPrototypeManager _protomanager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly ISharedPlayerManager _playerManager = default!;

        // SS14-Art-Edit start
        /// <summary>
        /// Cached persistent equipment for each character slot.
        /// Key: slot index, Value: equipment dictionary or null if not found.
        /// </summary>
        private readonly Dictionary<int, Dictionary<string, string>?> _persistentEquipmentCache = new();
        // SS14-Art-Edit end

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // SS14-Art-Edit start
            // Subscribe to persistent appearance responses
            _preferencesManager.PersistentAppearanceReceived += OnPersistentAppearanceReceived;
            // SS14-Art-Edit end

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            //_createNewCharacterButton = new Button
            //{
            //    Text = Loc.GetString("character-setup-gui-create-new-character-button"),
            //};

            //_createNewCharacterButton.OnPressed += args =>
            //{
            //    _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
            //    ReloadCharacterPickers();
            //    args.Event.Handle();
            //};

            CharEditor.AddChild(profileEditor);
            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
        }

        // SS14-Art-Edit start
        private void OnPersistentAppearanceReceived(MsgPersistentAppearance message)
        {
            _persistentEquipmentCache[message.Slot] = message.Found ? message.EquippedItems : null;
            
            RefreshCharacterPicker(message.Slot);

            // Update the lobby preview if this is the selected slot
            if (message.Slot == _preferencesManager.Preferences?.SelectedCharacterIndex)
            {
                var lobbyController = UserInterfaceManager.GetUIController<LobbyUIController>();
                lobbyController?.RefreshLobbyPreview();
                
                // Update the profile editor if it's open for this slot
                var profileEditor = FindProfileEditor();
                if (profileEditor != null && profileEditor.CharacterSlot == message.Slot)
                {
                    profileEditor.ReloadPreview();
                }
            }
        }

        private HumanoidProfileEditor? FindProfileEditor()
        {
            foreach (var child in CharEditor.Children)
            {
                if (child is HumanoidProfileEditor editor)
                    return editor;
            }
            return null;
        }

        private void RefreshCharacterPicker(int slot)
        {
            // Find and update the specific button for this slot
            foreach (var child in Characters.Children)
            {
                if (child is CharacterPickerButton button && button.Slot == slot)
                {
                    var profile = _preferencesManager.Preferences?.Characters.GetValueOrDefault(slot);
                    if (profile != null)
                    {
                        _persistentEquipmentCache.TryGetValue(slot, out var equipment);
                        button.UpdatePreview(profile, equipment);
                    }
                    break;
                }
            }
        }

        /// <summary>
        /// Gets the cached persistent equipment for a specific slot, if available.
        /// </summary>
        public Dictionary<string, string>? GetPersistentEquipment(int slot)
        {
            return _persistentEquipmentCache.GetValueOrDefault(slot);
        }
        // SS14-Art-Edit end

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            //   _createNewCharacterButton.Orphan();
            Characters.RemoveAllChildren();

            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            //_createNewCharacterButton.ToolTip =
            //    Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
            //        ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;
            
            // SS14-Art-Edit start
            // Clear cache before reload
          //  _persistentEquipmentCache.Clear();
            // SS14-Art-Edit end
            
            for (int i = 0; i < _preferencesManager.Settings!.MaxCharacterSlots; i++)
            {
                _preferencesManager.Preferences!.Characters.TryGetValue(i, out HumanoidCharacterProfile? characterProfile);
                
                // SS14-Art-Edit start
                // Try to get cached equipment, or request it if not cached
                _persistentEquipmentCache.TryGetValue(i, out var equipment);
                
                var characterPickerButton = new CharacterPickerButton(
                    _protomanager,
                    _playerManager,
                    characterButtonsGroup,
                    characterProfile,
                    i == selectedSlot,
                    i,
                    equipment);
                // SS14-Art-Edit end
                
                Characters.AddChild(characterPickerButton);
                var slot = i;
                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };

                // SS14-Art-Edit start
                // Request persistent appearance for this slot if profile exists and not cached
                if (characterProfile != null && !_persistentEquipmentCache.ContainsKey(i))
                {
                    _preferencesManager.RequestPersistentAppearance(i);
                }
                // SS14-Art-Edit end
            }

            //     _createNewCharacterButton.Disabled = numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            //     Characters.AddChild(_createNewCharacterButton);
        }

        // SS14-Art-Edit start
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _preferencesManager.PersistentAppearanceReceived -= OnPersistentAppearanceReceived;
        }
        // SS14-Art-Edit end
    }
}