using System.Linq;
using Content.Client.Humanoid;
using Content.Shared.Clothing;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Holds character data on the side of the setup GUI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CharacterPickerButton : ContainerButton
{
    /// <summary>
    /// Invoked if we should delete the attached character
    /// </summary>
    public event Action? OnDeletePressed;

    // SS14-Art-Edit start
    /// <summary>
    /// The character slot index for this button.
    /// </summary>
    public int Slot { get; private set; }

    private HumanoidCharacterProfile? _profile;
    private Dictionary<string, string>? _persistentEquipment;
    // SS14-Art-Edit end

    // SS14-Art-Edit start
    public CharacterPickerButton(
        IPrototypeManager prototypeManager,
        ISharedPlayerManager playerMan,
        ButtonGroup group,
        HumanoidCharacterProfile? profile,
        bool isSelected,
        int slot,
        Dictionary<string, string>? persistentEquipment = null)
    // SS14-Art-Edit end
    {
        RobustXamlLoader.Load(this);
        AddStyleClass(StyleClassButton);
        ToggleMode = true;
        Group = group;
        
        // SS14-Art-Edit start
        Slot = slot;
        _profile = profile;
        _persistentEquipment = persistentEquipment;
        // SS14-Art-Edit end
        
        var name = "Empty Slot";
        if (profile != null)
        {
            name = profile.Name;
            // SS14-Art-Edit start
            View.LoadPreview(profile, persistentEquipment: persistentEquipment);
            // SS14-Art-Edit end
        }
        var description = name;

        Pressed = isSelected;
        DeleteButton.Visible = !isSelected;

        DescriptionLabel.Text = description;

        ConfirmDeleteButton.OnPressed += _ =>
        {
            Parent?.RemoveChild(this);
            Parent?.RemoveChild(ConfirmDeleteButton);
            OnDeletePressed?.Invoke();
        };

        DeleteButton.OnPressed += _ =>
        {
            DeleteButton.Visible = false;
            ConfirmDeleteButton.Visible = true;
        };
    }

    // SS14-Art-Edit start
    /// <summary>
    /// Updates the preview with a new profile and/or equipment.
    /// </summary>
    public void UpdatePreview(HumanoidCharacterProfile profile, Dictionary<string, string>? persistentEquipment = null)
    {
        _profile = profile;
        _persistentEquipment = persistentEquipment;
        View.LoadPreview(profile, persistentEquipment: persistentEquipment);
        
        if (profile != null)
        {
            DescriptionLabel.Text = profile.Name;
        }
    }
    // SS14-Art-Edit end
}