using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Shared.CCVar;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Content.Shared._Art.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using System.Linq;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// If we're attempting to join.
        /// </summary>
        public event Action? Join;

        /// <summary>
        /// Entity used for the profile editor preview
        /// </summary>
        public EntityUid PreviewDummy;


        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        // SS14-Art-Edit start
        /// <summary>
        /// What the persistent (saved) body for <see cref="CharacterSlot"/> is currently
        /// wearing, as last reported by the server. Null if there is no saved body yet
        /// (character never entered cryosleep) or we haven't heard back yet.
        /// </summary>
        private Dictionary<string, string>? _persistentEquipment;
        // SS14-Art-Edit end

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private ISawmill _sawmill;

        public string ThresholdLore = "An area of space which has been unreachable due to cosmic storms which make long-distance FTL travel lethal to all intelligent creatures.\n\nNanotrasen has discovered a method to send living people into the Threshold by keeping them in cryosleep through the journey.\n\nNanotrasen has begun mass recruiting across the Galaxy in an effort to find people willing to leave everything behind and journey into the Threshold.\n\nThe Threshold is an extremely dangerous area of space with many secrets and mysteries including [bold]bluespace crystal[/bold].";
        public string NanotrasenLore = "An ultra large galactic RnD firm named Nanotrasen has begun sending colonists into the Threshold.\n\nThe colonists are expected to establish a variety of independent space stations within the Threshold to establish trade infrastructure.\n\nNanotrasen hopes that these stations will allow greater exploration and exploitation of the Threshold.";
        public Dictionary<string, string> Alignments = new Dictionary<string, string>
        {
            { "Lawful Good", "[bold]'Justice'[/bold]\n\nBanish evil through higher authority.\nYou believe law and order is the best way to help others." },
            { "Good", "[bold]'Temperance'[/bold]\n\nHeal the universe through kindness.\nYou have a strong conviction towards helping others, no matter the cost." },
            { "Chaotic Good", "[bold]'Strength'[/bold]\n\nSet others free from evil.\nYou believe freedom from tyranny is the best way to help others." },
            { "Lawful", "[bold]'The Chariot'[/bold]\n\nBring the universe into order.\nYou value law and well ordered society above all else." },
            { "True Neutral", "[bold]'The Hermit'[/bold]\n\nIn all things, the middle way.\nYou have no strong preference between law and freedom and do not go out of your way to help or harm others." },
            { "Chaotic", "[bold]'The Moon'[/bold]\n\nUntether yourself from all obligations.\nYou value your own personal freedom above all else." },
            { "Lawful Evil", "[bold]'The Emperor'[/bold]\n\nRule others with an iron first.\nYou believe order and hierarchy are tools to personally benefit you." },
            { "Evil", "[bold]'Death'[/bold]\n\nPut yourself before all others.\nYou have no true regard for others and act only to benefit yourself." },
            { "Chaotic Evil", "[bold]'The Devil'[/bold]\n\nFreedom at any cost.\nYou hate authority and will seek freedom and personal gratification even when it harms others." },

        };

        public Dictionary<string, string> Sigils = new Dictionary<string, string>
        {
            { "The Whale", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a whale. When it opens its mouth it reveals a giant blue crystal protruding up from its throat.\n\nYour shipmates haul it aboard and start butchering it. The fumes make your eyes and mouth burn viciously." },
            { "The Lock", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a lock. It holds the doors of your cage shut until the day of your execution.\n\nAfter you die you still aren't free, as they put your soul into a vault. All you can see is the lock." },
            { "The Show", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a show. It's the story of your life as a show. In the show you are rejected from joining the crew into the Threshold.\n\nThe show continues on but you cant keep watching it. The signal cant reach." },
            { "The Thought", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a thought. It exists in two places at once and what else could?\n\nIt clamors upwards and happily takes its place along with the others. They are building a gate." },
            { "The Void", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold the void grows even darker than pitch. You hit the surface of nothingness and go beneath the waters\n\nIt's so cold and when you look up you see yourself looking down at a reflection." }
        };

        public Dictionary<string, string> Backgrounds = new Dictionary<string, string>
        {
            { "Corporate Space Station", "You have worked aboard a large space station for one of the galaxies largest ultra-mega-corps. You didn't get many breaks." },
            { "Labor World", "You lived on an impoverished world where everyone worked all the time to produce profit for off-world shareholders." },
            { "War Cursed World", "You lived on a world which is a constant warzone. Survival was a desperate prospect." },
            { "Suburb World", "You lived on a underpopulated and unimportant world. It wasn't a very exciting place." },
            { "Core World", "You lived on a world controlled by the Solar Legion, one of the wealthiest Empires in the Galaxy. The planet was in decline." },
            { "Commune", "You lived as part of a communist refuge. Supplies were very limited." }
        };

        public Dictionary<string, string> Motives = new Dictionary<string, string>
        {
            { "Wealth", "The Threshold offers the promise of eternal riches to those bold enough to seize them." },
            { "Power", "You are tired of submitting to the authority of others. Within the Threshold you will build your perfect world." },
            { "Secret Knowledge", "The last frontiers of science may be hidden within the Threshold. You intend to discover them." },
            { "Friendship", "You want to be well liked and to know many people." },
            { "Enlightenment", "Rumors swirl that the Gods from a different universe dwell at the edges of the Threshold." }
        };
        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            // SS14-Art-Edit start
            _preferencesManager.PersistentAppearanceReceived += OnPersistentAppearanceReceived;
            // SS14-Art-Edit end
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            foreach (var kv in Alignments)
            {
                AlignmentButton.AddItem(kv.Key);

            }
            AlignmentButton.OnItemSelected += args =>
            {
                var e = Alignments.ElementAt(args.Id);
                AlignTitleLabel.Text = e.Key;
                AlignDescLabel.Text = e.Value;
                AlignmentButton.SelectId(args.Id);
            };
            AlignmentButton.Select(4);
            var e = Alignments.ElementAt(4);
            AlignTitleLabel.Text = e.Key;
            AlignDescLabel.Text = e.Value;
            foreach (var kv in Backgrounds)
            {
                BGButton.AddItem(kv.Key);
            }
            BGButton.OnItemSelected += args =>
            {
                var e = Backgrounds.ElementAt(args.Id);
                BGTitleLabel.Text = e.Key;
                BGDescLabel.Text = e.Value;
                BGButton.SelectId(args.Id);
            };
            BGButton.Select(0);
            e = Backgrounds.ElementAt(0);
            BGTitleLabel.Text = e.Key;
            BGDescLabel.Text = e.Value;
            foreach (var kv in Motives)
            {
                MotiveButton.AddItem(kv.Key);
            }
            MotiveButton.OnItemSelected += args =>
            {
                var e = Motives.ElementAt(args.Id);
                MotiveTitleLabel.Text = e.Key;
                MotiveDescLabel.Text = e.Value;
                MotiveButton.SelectId(args.Id);
            };
            MotiveButton.Select(3);
            e = Motives.ElementAt(3);
            MotiveTitleLabel.Text = e.Key;
            MotiveDescLabel.Text = e.Value;
            ThresholdLoreLabel.Text = ThresholdLore;
            NanotrasenLabel.Text = NanotrasenLore;
            foreach (var kv in Sigils)
            {
                SigilButton.AddItem(kv.Key);
            }
            SigilButton.OnItemSelected += args =>
            {
                var e = Sigils.ElementAt(args.Id);
                SigilTitle.Text = e.Key;
                SigilLabel.Text = e.Value;
                SigilButton.SelectId(args.Id);
            };
            SigilButton.Select(0);
            e = Sigils.ElementAt(0);
            SigilTitle.Text = e.Key;
            SigilLabel.Text = e.Value;

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };
            JoinGameButton.OnPressed += args =>
            {
                Join?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
            };

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs


            RefreshTraits();

            #region Markings


            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            if (Profile == null)
            {
                Profile = new HumanoidCharacterProfile();
                RandomizeEverything();
            }
            SetDirty();
        }

        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        //public void RefreshFlavorText()
        //{
        //    if (_allowFlavorText)
        //    {
        //        if (_flavorText != null)
        //            return;

        //        _flavorText = new FlavorText.FlavorText();
        //        TabContainer.AddChild(_flavorText);
        //        TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));
        //        _flavorTextEdit = _flavorText.CFlavorTextInput;

        //        _flavorText.OnFlavorTextChanged += OnFlavorTextChange;
        //    }
        //    else
        //    {
        //        if (_flavorText == null)
        //            return;

        //        TabContainer.RemoveChild(_flavorText);
        //        _flavorText.OnFlavorTextChanged -= OnFlavorTextChange;
        //        _flavorText.Dispose();
        //        _flavorTextEdit?.Dispose();
        //        _flavorTextEdit = null;
        //        _flavorText = null;
        //    }
        //}

        /// <summary>
        /// Refreshes traits selector
        /// </summary>
        //public void RefreshTraits()
        //{

        //}

        /// <summary>
        /// Refreshes the species selector.
        /// </summary>
        //public void RefreshSpecies()
        //{
        //    SpeciesButton.Clear();
        //    _species.Clear();

        //    _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
        //    _species.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
        //    var speciesIds = _species.Select(o => o.ID).ToList();

        //    for (var i = 0; i < _species.Count; i++)
        //    {
        //        var name = Loc.GetString(_species[i].Name);
        //        SpeciesButton.AddItem(name, i);

        //        if (Profile?.Species.Equals(_species[i].ID) == true)
        //        {
        //            SpeciesButton.SelectId(i);
        //        }
        //    }

        //    // If our species isn't available then reset it to default.
        //    if (Profile != null)
        //    {
        //        if (!speciesIds.Contains(Profile.Species))
        //        {
        //            SetSpecies(SharedHumanoidAppearanceSystem.DefaultSpecies);
        //        }
        //    }
        //}

        //public void RefreshAntags()
        //{

        //}

        private void SetDirty()
        {
            if (Profile == null)
            {
                Profile = new HumanoidCharacterProfile();
                RandomizeEverything();
            }
            ImportButton.Visible = false;
            ExportButton.Visible = false;
            ExportImageButton.Visible = false;
            ResetButton.Visible = false;
            OpenImagesButton.Visible = false;

            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter == null)
            {
                IsDirty = true;
                TabContainer.Visible = true;
                SaveButton.Visible = true;
                JoinGameButton.Visible = false;
                RandomizeEverythingButton.Visible = true;
                NameRandomize.Visible = true;
                NameEdit.Editable = true;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = false;
            TabContainer.Visible = false;
            SaveButton.Visible = false;
            JoinGameButton.Visible = true;
            RandomizeEverythingButton.Visible = false;
            NameRandomize.Visible = false;
            NameEdit.Editable = false;
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        public void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed, _persistentEquipment); // SS14-Art-Edit: _persistentEquipment

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            SetDirty();
            JobOverride = null;

            // SS14-Art-Edit start
            // Try to get cached equipment from CharacterSetupGui first
            if (slot != null)
            {
                var parent = Parent;
                while (parent != null && parent is not CharacterSetupGui)
                    parent = parent.Parent;
                
                if (parent is CharacterSetupGui setupGui)
                {
                    // Use cached equipment immediately if available
                    _persistentEquipment = setupGui.GetPersistentEquipment(slot.Value);
                }
                else
                {
                    _persistentEquipment = null;
                }
                
                // Always request fresh data from server
                _preferencesManager.RequestPersistentAppearance(slot.Value);
            }
            else
            {
                _persistentEquipment = null;
            }
            // SS14-Art-Edit end

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();

            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();

            //if (Profile != null)
            //{
            //    PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            //}
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        // SS14-Art-Edit start
        private void OnPersistentAppearanceReceived(MsgPersistentAppearance message)
        {
            // Stale response for a slot we've since navigated away from - ignore it.
            if (message.Slot != CharacterSlot)
                return;

            _persistentEquipment = message.Found ? message.EquippedItems : null;
            ReloadPreview();
        }
        // SS14-Art-Edit end

        //private void OnSpeciesInfoButtonPressed(BaseButton.ButtonEventArgs args)
        //{
        //    // TODO GUIDEBOOK
        //    // make the species guide book a field on the species prototype.
        //    // I.e., do what jobs/antags do.

        //    var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
        //    var species = Profile?.Species ?? SharedHumanoidAppearanceSystem.DefaultSpecies;
        //    var page = DefaultSpeciesGuidebook;
        //    if (_prototypeManager.HasIndex<GuideEntryPrototype>(species))
        //        page = new ProtoId<GuideEntryPrototype>(species.Id); // Gross. See above todo comment.

        //    if (_prototypeManager.Resolve(DefaultSpeciesGuidebook, out var guideRoot))
        //    {
        //        var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>();
        //        dict.Add(DefaultSpeciesGuidebook, guideRoot);
        //        //TODO: Don't close the guidebook if its already open, just go to the correct page
        //        guidebookController.OpenGuidebook(dict, includeChildren:true, selected: page);
        //    }
        //}

        /// <summary>
        /// Refreshes all job selectors.
        /// </summary>
        //public void RefreshJobs()
        //{

        //}

        //private void OpenLoadout(JobPrototype? jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto)
        //{
        //    _loadoutWindow?.Dispose();
        //    _loadoutWindow = null;
        //    var collection = IoCManager.Instance;

        //    if (collection == null || _playerManager.LocalSession == null || Profile == null)
        //        return;

        //    JobOverride = jobProto;
        //    var session = _playerManager.LocalSession;

        //    _loadoutWindow = new LoadoutWindow(Profile, roleLoadout, roleLoadoutProto, _playerManager.LocalSession, collection)
        //    {
        //        Title = Loc.GetString("loadout-window-title-loadout", ("job", $"{jobProto?.LocalizedName}")),
        //    };

        //    // Refresh the buttons etc.
        //    _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
        //    _loadoutWindow.OpenCenteredLeft();

        //    _loadoutWindow.OnNameChanged += name =>
        //    {
        //        roleLoadout.EntityName = name;
        //        Profile = Profile.WithLoadout(roleLoadout);
        //        SetDirty();
        //    };

        //    _loadoutWindow.OnLoadoutPressed += (loadoutGroup, loadoutProto) =>
        //    {
        //        roleLoadout.AddLoadout(loadoutGroup, loadoutProto, _prototypeManager);
        //        _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
        //        Profile = Profile?.WithLoadout(roleLoadout);
        //        ReloadPreview();
        //    };

        //    _loadoutWindow.OnLoadoutUnpressed += (loadoutGroup, loadoutProto) =>
        //    {
        //        roleLoadout.RemoveLoadout(loadoutGroup, loadoutProto, _prototypeManager);
        //        _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
        //        Profile = Profile?.WithLoadout(roleLoadout);
        //        ReloadPreview();
        //    };

        //    JobOverride = jobProto;
        //    ReloadPreview();

        //    _loadoutWindow.OnClose += () =>
        //    {
        //        JobOverride = null;
        //        ReloadPreview();
        //    };

        //    if (Profile is null)
        //        return;

        //    UpdateJobPriorities();
        //}

        //private void OnFlavorTextChange(string content)
        //{
        //    if (Profile is null)
        //        return;

        //    Profile = Profile.WithFlavorText(content);
        //    SetDirty();
        //}

        //private void OnMarkingChange(MarkingSet markings)
        //{
        //    if (Profile is null)
        //        return;

        //    Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(markings.GetForwardEnumerator().ToList()));
        //    ReloadProfilePreview();
        //}

        //private void OnSkinColorOnValueChanged()
        //{
        //    if (Profile is null) return;

        //    var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
        //    var strategy = _prototypeManager.Index(skin).Strategy;

        //    switch (strategy.InputType)
        //    {
        //        case SkinColorationStrategyInput.Unary:
        //        {
        //            if (!Skin.Visible)
        //            {
        //                Skin.Visible = true;
        //                RgbSkinColorContainer.Visible = false;
        //            }

        //            var color = strategy.FromUnary(Skin.Value);

        //            Markings.CurrentSkinColor = color;
        //            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

        //            break;
        //        }
        //        case SkinColorationStrategyInput.Color:
        //        {
        //            if (!RgbSkinColorContainer.Visible)
        //            {
        //                Skin.Visible = false;
        //                RgbSkinColorContainer.Visible = true;
        //            }

        //            var color = strategy.ClosestSkinColor(_rgbSkinColorSelector.Color);

        //            Markings.CurrentSkinColor = color;
        //            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

        //            break;
        //        }
        //    }

        //    ReloadProfilePreview();
        //}

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            // SS14-Art-Edit start
            _preferencesManager.PersistentAppearanceReceived -= OnPersistentAppearanceReceived;
            // SS14-Art-Edit end

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

        //private void RandomizeEverything()
        //{
        //    if(Profile != null)
        //         Profile = HumanoidCharacterProfile.RandomWithSpecies(Profile.Species);
        //    else
        //        Profile = HumanoidCharacterProfile.Random();
        //    SetProfile(Profile, CharacterSlot);
        //    SetDirty();
        //}

        //private void RandomizeName()
        //{
        //    if (Profile == null) return;
        //    var name = HumanoidCharacterProfile.GetName(Profile.Species, Profile.Gender);
        //    SetName(name);
        //    UpdateNameEdit();
        //}


    }
}
