using Content.Shared.Preferences;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    public Button CharacterSetupButton => CharacterSetup;

    // SS14-Art-Edit start
    private HumanoidCharacterProfile? _currentProfile;
    private Dictionary<string, string>? _currentEquipment;
    // SS14-Art-Edit end

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    // SS14-Art-Edit start
    /// <summary>
    /// Loads the character preview with the given profile and optional persistent equipment.
    /// </summary>
    public void LoadPreview(HumanoidCharacterProfile profile, Dictionary<string, string>? persistentEquipment = null)
    {
        _currentProfile = profile;
        _currentEquipment = persistentEquipment;
        ProfilePreviewSpriteView.LoadPreview(profile, persistentEquipment: persistentEquipment);
        SetSummaryText(profile.Summary);
    }

    /// <summary>
    /// Updates the preview with new persistent equipment without reloading the entire profile.
    /// </summary>
    public void UpdateEquipment(Dictionary<string, string>? persistentEquipment)
    {
        _currentEquipment = persistentEquipment;
        if (_currentProfile != null)
        {
            ProfilePreviewSpriteView.LoadPreview(_currentProfile, persistentEquipment: persistentEquipment);
        }
    }

    /// <summary>
    /// Clears the preview.
    /// </summary>
    public void ClearPreview()
    {
        _currentProfile = null;
        _currentEquipment = null;
        ProfilePreviewSpriteView.ClearPreview();
        SetSummaryText(string.Empty);
    }
    // SS14-Art-Edit end
}
